In [1]:
import torch

In [2]:
import torchvision.datasets as datasets

In [24]:
from torch.utils.data import DataLoader 
from torchvision import transforms
import torch.nn as nn

In [25]:
train_CIFAR_set = datasets.CIFAR10(root="./datasets/", train=True, transform=transforms.ToTensor(), download=False)

In [26]:
test_CIFAR_set = datasets.CIFAR10(root="./datasets/", train=False, transform=transforms.ToTensor(),download=False)

In [27]:
train_loader = DataLoader(train_CIFAR_set, batch_size=64,shuffle=True)

In [28]:
test_loader = DataLoader(test_CIFAR_set, batch_size=64, shuffle=False)

In [31]:
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.seqential = nn.Sequential(nn.Conv2d(3, 32, 5, padding=2),
                                      nn.MaxPool2d(2),
                                      nn.Conv2d(32,32,5,padding=2),
                                      nn.MaxPool2d(2),
                                      nn.Conv2d(32,64,5,padding=2),
                                      nn.MaxPool2d(2),
                                      nn.Flatten(),
                                      nn.Linear(1024,64),
                                      nn.ReLU(),
                                      nn.Linear(64,10),
                                      nn.Sigmoid()
                                      )
    def forward(self, x):
        x = self.seqential(x)
        return x

In [32]:
m = Model()

In [33]:
m

Model(
  (seqential): Sequential(
    (0): Conv2d(3, 32, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (2): Conv2d(32, 32, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (4): Conv2d(32, 64, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (5): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (6): Flatten(start_dim=1, end_dim=-1)
    (7): Linear(in_features=1024, out_features=64, bias=True)
    (8): ReLU()
    (9): Linear(in_features=64, out_features=10, bias=True)
    (10): Sigmoid()
  )
)

In [38]:
x = torch.tensor([1,2,3],dtype=torch.float32)
y = torch.tensor([1,2,5],dtype=torch.float32)

In [40]:
loss = nn.L1Loss()

In [41]:
loss(x,y)

tensor(0.6667)

In [42]:
x = torch.reshape(x, (1,1,1,-1))

In [43]:
x.shape

torch.Size([1, 1, 1, 3])

In [44]:
y = torch.reshape(y, (1,1,1,-1))

In [45]:
loss(x,y)

tensor(0.6667)

In [46]:
loss = nn.MSELoss()

In [47]:
loss(x,y)

tensor(1.3333)

In [3]:
import torch
import torch.nn as nn

In [11]:
x = torch.rand([1,16,7,7], requires_grad=True)

In [12]:
x.shape

torch.Size([1, 16, 7, 7])

In [13]:
layer = nn.BatchNorm2d(16)

In [14]:
out = layer(x)

In [15]:
out

tensor([[[[ 5.3020e-01,  7.0915e-01,  9.7028e-01, -1.5251e+00, -6.5370e-01,
           -2.1160e-01, -8.9698e-01],
          [-7.5551e-01,  5.5573e-01, -1.0690e+00,  7.8139e-01,  1.2510e+00,
           -8.2756e-01, -1.0921e+00],
          [ 1.5706e+00,  1.4841e+00, -7.7421e-01, -1.0416e+00, -1.4216e+00,
           -1.3557e+00,  1.9141e-01],
          [ 3.4659e-03, -1.1760e+00,  4.5511e-03,  5.8455e-01, -1.1993e+00,
           -7.2712e-01, -1.0281e+00],
          [-6.9066e-01,  5.8814e-01,  1.8417e+00,  1.2441e+00, -1.4753e+00,
           -3.8453e-02,  6.4459e-01],
          [-5.2134e-01,  1.2901e+00,  4.0321e-01,  6.0540e-01,  4.0393e-02,
            9.7603e-01,  1.0882e+00],
          [ 1.4374e+00,  1.2392e+00, -8.9269e-01, -4.2544e-01, -5.9700e-01,
            1.7023e+00, -1.3412e+00]],

         [[ 7.4177e-01,  5.1381e-01, -1.3401e+00, -3.0166e-01, -2.9604e-01,
           -1.3141e+00, -1.2070e+00],
          [ 7.6815e-01,  1.2690e-01, -1.3553e+00,  1.1444e+00,  1.4395e+00,
          

In [17]:
layer.weight

Parameter containing:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       requires_grad=True)

In [18]:
layer.bias

Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       requires_grad=True)

In [19]:
vars(layer)

{'training': True, '_parameters': OrderedDict([('weight', Parameter containing:
               tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
                      requires_grad=True)), ('bias', Parameter containing:
               tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
                      requires_grad=True))]), '_buffers': OrderedDict([('running_mean',
               tensor([0.0438, 0.0567, 0.0493, 0.0538, 0.0441, 0.0515, 0.0520, 0.0507, 0.0538,
                       0.0379, 0.0497, 0.0459, 0.0506, 0.0471, 0.0510, 0.0480])),
              ('running_var',
               tensor([0.9083, 0.9074, 0.9079, 0.9118, 0.9089, 0.9094, 0.9091, 0.9068, 0.9065,
                       0.9075, 0.9097, 0.9082, 0.9094, 0.9088, 0.9065, 0.9072])),
              ('num_batches_tracked',
               tensor(1))]), '_non_persistent_buffers_set': set(), '_backward_hooks': OrderedDict(), '_is_full_backward_hook': None, '_forward_hooks': OrderedD

In [20]:
1024*32*32

1048576